import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'
import path from 'path'

const SECONDS_PER_DAY = 24 * 60 * 60
const SECONDS_PER_YEAR = 365 * SECONDS_PER_DAY

const CACHE_TTL = {
  TF_MODELS: 90 * SECONDS_PER_DAY,
  GOOGLE_FONTS: SECONDS_PER_YEAR,
  SUPABASE_STORAGE: 7 * SECONDS_PER_DAY,
  IMAGES: 30 * SECONDS_PER_DAY,
} as const

const CACHE_MAX_ENTRIES = {
  SUPABASE_STORAGE: 100,
  IMAGES: 60,
} as const

const SUPABASE_STORAGE_NETWORK_TIMEOUT_S = 5

// Resolve `base` at config-load time. Read from .env files (envDir '../') AND
// shell env (process.env wins via loadEnv merge). Default '/' for sub-path
// portability on Imperial; Cloudflare Pages sets VITE_BASE_PATH=/ so absolute
// asset URLs work with SPA fallback at deep URLs. Normalize to ensure a
// trailing slash so values like '/foo' don't produce '/fooassets/...'.
function resolveBase(mode: string): string {
  const env = loadEnv(mode, '../', 'VITE_')
  const raw = (env.VITE_BASE_PATH ?? '').trim()
  if (raw === '') return './'
  return raw.endsWith('/') ? raw : raw + '/'
}

export default defineConfig(({ mode }) => ({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      registerType: 'prompt',
      includeAssets: ['vite.svg'],
      manifest: {
        name: 'sp(eye) - Adaptive Speed Reading',
        short_name: 'sp(eye)',
        description:
          'An adaptive speed reading platform with eye-tracking technology',
        theme_color: '#1a1a2e',
        background_color: '#1a1a2e',
        display: 'standalone',
        start_url: './?source=pwa',
        scope: './',
        // Icons are generated by scripts/generate-pwa-icons.mjs from
        // favicons/svg/pwa_icon.svg as part of the prebuild step.
        // `purpose: 'any'` is the W3C default but stated explicitly here
        // alongside the maskable entry so the two purposes read in parallel.
        icons: [
          {
            src: 'pwa-192x192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: 'pwa-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: 'pwa-maskable-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,svg,png,woff2}'],
        globIgnores: ['**/models/**'],
        navigateFallback: 'index.html',
        navigateFallbackDenylist: [/^\/rest\/v1\//, /^\/auth\//],
        runtimeCaching: [
          {
            urlPattern:
              /^https:\/\/cdn\.jsdelivr\.net\/npm\/(@mediapipe|@tensorflow)/,
            handler: 'CacheFirst',
            options: {
              cacheName: 'tf-models',
              expiration: { maxAgeSeconds: CACHE_TTL.TF_MODELS },
            },
          },
          {
            urlPattern: /^https:\/\/fonts\.googleapis\.com/,
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts-stylesheets',
              expiration: { maxAgeSeconds: CACHE_TTL.GOOGLE_FONTS },
            },
          },
          {
            urlPattern: /^https:\/\/fonts\.gstatic\.com/,
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts-webfonts',
              expiration: { maxAgeSeconds: CACHE_TTL.GOOGLE_FONTS },
            },
          },
          // Supabase Storage (avatars, user uploads) — NetworkFirst so updates are reflected promptly; falls back to cache when offline.
          {
            urlPattern: /\/storage\/v1\//,
            handler: 'NetworkFirst',
            options: {
              cacheName: 'supabase-storage',
              networkTimeoutSeconds: SUPABASE_STORAGE_NETWORK_TIMEOUT_S,
              expiration: {
                maxAgeSeconds: CACHE_TTL.SUPABASE_STORAGE,
                maxEntries: CACHE_MAX_ENTRIES.SUPABASE_STORAGE,
              },
            },
          },
          {
            urlPattern: /\.(?:png|jpg|jpeg|svg|gif|webp)$/,
            handler: 'CacheFirst',
            options: {
              cacheName: 'images',
              expiration: {
                maxAgeSeconds: CACHE_TTL.IMAGES,
                maxEntries: CACHE_MAX_ENTRIES.IMAGES,
              },
            },
          },
          {
            urlPattern: /\/rest\/v1\//,
            handler: 'NetworkOnly',
          },
        ],
      },
    }),
  ],
  base: resolveBase(mode),
  envDir: '../',
  resolve: {
    alias: {
      webgazer: path.resolve(__dirname, 'src/lib/webgazer-local/src/index.mjs'),
    },
  },
  optimizeDeps: {
    include: [
      '@tensorflow/tfjs',
      '@tensorflow-models/face-landmarks-detection',
      'localforage',
      'regression',
    ],
  },
}))
