export const MAX_TITLE_CHARACTERS = 100
export const MAX_CONTENT_CHARACTERS = 15000
export const MAX_SECTIONS = 50

export const TITLE_CHARACTER_WARNING_THRESHOLD = 0.8
export const CONTENT_CHARACTER_WARNING_THRESHOLD = 0.8
export const SECTION_WARNING_THRESHOLD = 0.8
