export const libraryTexts = [
  {
    id: 'text-1',
    title: 'The Great Adventure',
    preview:
      'Once upon a time in a faraway land, there lived a brave explorer.',
    has_summary: true,
    uploaded_at: '2025-01-15T10:00:00Z',
    owner_id: 'user-1',
    quiz: null,
    fiction: true,
    complexity: 3,
    source: null,
    processing_status: 'completed' as const,
    quiz_valid: true,
    llm_decision: 'approved' as const,
    llm_violation_type: null,
    admin_decision: 'approved' as const,
    admin_reviewed_by: null,
    admin_reviewed_at: null,
    rejection_reason: null,
    rejection_stage: null,
  },
  {
    id: 'text-2',
    title: 'Understanding AI',
    preview:
      'Artificial intelligence is transforming how we interact with technology.',
    has_summary: true,
    uploaded_at: '2025-02-10T14:30:00Z',
    owner_id: 'user-1',
    quiz: null,
    fiction: false,
    complexity: 7,
    source: 'MIT Technology Review',
    processing_status: 'completed' as const,
    quiz_valid: true,
    llm_decision: 'approved' as const,
    llm_violation_type: null,
    admin_decision: 'approved' as const,
    admin_reviewed_by: null,
    admin_reviewed_at: null,
    rejection_reason: null,
    rejection_stage: null,
  },
  {
    id: 'text-3',
    title: 'Climate Change Report',
    preview:
      'Global temperatures have risen significantly over the past century.',
    has_summary: false,
    uploaded_at: '2025-03-05T09:15:00Z',
    owner_id: 'user-1',
    quiz: null,
    fiction: false,
    complexity: 5,
    source: null,
    processing_status: 'pending' as const,
    quiz_valid: null,
    llm_decision: null,
    llm_violation_type: null,
    admin_decision: null,
    admin_reviewed_by: null,
    admin_reviewed_at: null,
    rejection_reason: null,
    rejection_stage: null,
  },
  {
    id: 'text-4',
    title: 'Short Story Collection',
    preview:
      'The rain fell softly on the window pane as she opened the letter.',
    has_summary: true,
    uploaded_at: '2025-01-20T16:45:00Z',
    owner_id: 'user-2',
    quiz: null,
    fiction: true,
    complexity: 2,
    source: null,
    processing_status: 'completed' as const,
    quiz_valid: true,
    llm_decision: 'approved' as const,
    llm_violation_type: null,
    admin_decision: 'approved' as const,
    admin_reviewed_by: null,
    admin_reviewed_at: null,
    rejection_reason: null,
    rejection_stage: null,
  },
  {
    id: 'text-5',
    title: 'Failed Processing Text',
    preview: 'This text had issues during processing.',
    has_summary: false,
    uploaded_at: '2025-04-01T12:00:00Z',
    owner_id: 'user-1',
    quiz: null,
    fiction: false,
    complexity: null,
    source: null,
    processing_status: 'failed' as const,
    quiz_valid: null,
    llm_decision: null,
    llm_violation_type: null,
    admin_decision: null,
    admin_reviewed_by: null,
    admin_reviewed_at: null,
    rejection_reason: null,
    rejection_stage: 'process_text' as const,
  },
  {
    id: 'text-6',
    title: 'Quantum Physics Basics',
    preview:
      'Quantum mechanics describes the behavior of particles at the atomic scale.',
    has_summary: true,
    uploaded_at: '2025-02-28T08:00:00Z',
    owner_id: 'user-1',
    quiz: null,
    fiction: false,
    complexity: 9,
    source: 'Nature',
    processing_status: 'completed' as const,
    quiz_valid: true,
    llm_decision: 'approved' as const,
    llm_violation_type: null,
    admin_decision: 'approved' as const,
    admin_reviewed_by: null,
    admin_reviewed_at: null,
    rejection_reason: null,
    rejection_stage: null,
  },
]

export const pendingApprovals = [
  {
    id: 'pending-1',
    title: 'Suspicious Content',
    content: 'Some flagged content here.',
    uploaded_at: '2025-03-10T08:00:00Z',
    owner_id: 'user-3',
    fiction: false,
    complexity: 5,
    processing_status: 'completed' as const,
    quiz_valid: true,
    llm_decision: 'rejected' as const,
    llm_violation_type: 'inappropriate_content',
    admin_decision: 'pending' as const,
    admin_reviewed_by: null,
    admin_reviewed_at: null,
    rejection_reason: null,
    // TOS violation: rejection_stage='process_text' + llm_violation_type set -> flagged
    rejection_stage: 'process_text' as const,
    quiz: null,
    source: null,
    summary: null,
    owner_username: 'flaggeduser',
  },
  {
    id: 'pending-2',
    title: 'Good Article',
    content: 'A well-written article about science.',
    uploaded_at: '2025-03-11T10:00:00Z',
    owner_id: 'user-4',
    fiction: false,
    complexity: 6,
    processing_status: 'completed' as const,
    quiz_valid: true,
    llm_decision: 'approved' as const,
    llm_violation_type: null,
    admin_decision: 'pending' as const,
    admin_reviewed_by: null,
    admin_reviewed_at: null,
    rejection_reason: null,
    rejection_stage: null,
    quiz: null,
    source: null,
    summary: null,
    // awaiting_review: no flags -> passed tab
    owner_username: 'gooduser',
  },
]

/**
 * Helper to generate a question set with 5 questions of 4 options each.
 * See lib/quizConstants.ts for valid quiz structure constraints.
 */
function makeQuestionSet(prefix: string) {
  return {
    questions: [
      {
        question: `${prefix} What is the main topic of the text?`,
        options: ['Science', 'History', 'Adventure', 'Technology'],
        correctAnswer: 0,
      },
      {
        question: `${prefix} Who is the main character?`,
        options: ['A scientist', 'An explorer', 'A teacher', 'A student'],
        correctAnswer: 1,
      },
      {
        question: `${prefix} Where does the story take place?`,
        options: ['A city', 'A forest', 'A faraway land', 'A school'],
        correctAnswer: 2,
      },
      {
        question: `${prefix} When does the story happen?`,
        options: ['Morning', 'Afternoon', 'Evening', 'Night'],
        correctAnswer: 0,
      },
      {
        question: `${prefix} What is the tone of the text?`,
        options: ['Serious', 'Humorous', 'Dramatic', 'Neutral'],
        correctAnswer: 3,
      },
    ],
  }
}

export const quizData = {
  questionSets: [
    makeQuestionSet('Set1'),
    makeQuestionSet('Set2'),
    makeQuestionSet('Set3'),
    makeQuestionSet('Set4'),
    makeQuestionSet('Set5'),
  ],
}
